# Generated by Django 5.0.4 on 2024-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='age',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
    ]
