# Generated by Django 5.0.6 on 2024-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_alter_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='asdfghjkl123', max_length=255),
        ),
    ]
