# Generated by Django 5.0.4 on 2024-05-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_language_remove_snippet_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
    ]
