# Generated by Django 5.0.4 on 2024-05-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_doctor_patient_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
