# Generated by Django 5.0.4 on 2024-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
