# Generated by Django 5.0.4 on 2024-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrail', '0002_trails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='pincode',
            field=models.IntegerField(default=416204),
        ),
    ]
