# Generated by Django 5.0.4 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrail', '0003_trails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='pincode',
            field=models.IntegerField(default=444),
        ),
    ]
