# Generated by Django 5.0.4 on 2024-04-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltrail', '0004_alter_trails_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trails',
            name='pincode',
        ),
    ]
